services:
  db:
    image: postgres:15
    container_name: postgres_db_estate
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: estate
    ports:
      - "5434:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
